db_file: "bot.db"

bot_url: "https://t.me/poket_codeboris_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке: \n%s"
    already_authorized: "Вы уже авторизованы. Присылайте ссылку, я её сохраню в pocket."
    save_successfully: "Ссылка успешно сохранена."
    unknow_command: "Я не знаю такой команды :("
  errors:
    default: "Произошла неизвестная ошибка."
    invalid_url: "Это не валидная ссылка."
    unauthorized: "Ты не авторизирован. Используй команду /start"
    unable_to_save: "Увы, не удалось сохранить ссылку. Попробуйте еще раз позже."